/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  items?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  clerkUserId?: string;
  email?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  stripePaymentId?: string;
  createdAt?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  material?: "wood" | "metal" | "fabric" | "leather" | "glass";
  color?: "black" | "white" | "oak" | "walnut" | "grey" | "natural";
  dimensions?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  featured?: boolean;
  assemblyRequired?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  clerkUserId?: string;
  stripeCustomerId?: string;
  createdAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Order | Product | SanityImageCrop | SanityImageHotspot | Slug | Category | Customer | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[   _type == "category" ] | order(title asc) {   _id,                   title,                 "slug": slug.current,  "image": image {         asset-> {               _id,                   url                 },                     hotspot            }}
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[  _type == "category"  && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  "image": image{    asset->{      _id,      url    },    hotspot  }}
export type CATEGORY_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: ./sanity/queries/customers.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[  _type == "customer"  && email == $email][0] {  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_EMAIL_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;
// Variable: CUSTOMER_BY_STRIPE_ID_QUERY
// Query: *[  _type == "customer"  && stripeCustomerId == $stripeCustomerId][0] {  _id,  email,  name,  clerkUserId,  stripeCustomerId,  createdAt}
export type CUSTOMER_BY_STRIPE_ID_QUERYResult = {
  _id: string;
  email: string | null;
  name: string | null;
  clerkUserId: string | null;
  stripeCustomerId: string | null;
  createdAt: string | null;
} | null;

// Source: ./sanity/queries/orders.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[  _type == "order"  && clerkUserId == $clerkUserId] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  "itemNames": items[].product->name,  "itemImages": items[].product->images[0].asset->url}
export type ORDERS_BY_USER_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
  itemImages: Array<string | null> | null;
}>;
// Variable: ORDER_BY_ID_QUERY
// Query: *[  _type == "order"  && _id == $id][0] {  _id,  orderNumber,  clerkUserId,  email,  items[]{    _key,    quantity,    priceAtPurchase,    product->{      _id,      name,      "slug": slug.current,      "image": images[0]{        asset->{          _id,          url        }      }    }  },  total,  status,  address{    name,    line1,    line2,    city,    postcode,    country  },  stripePaymentId,  createdAt}
export type ORDER_BY_ID_QUERYResult = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  email: string | null;
  items: Array<{
    _key: string;
    quantity: number | null;
    priceAtPurchase: number | null;
    product: {
      _id: string;
      name: string | null;
      slug: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  address: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    postcode: string | null;
    country: string | null;
  } | null;
  stripePaymentId: string | null;
  createdAt: string | null;
} | null;
// Variable: RECENT_ORDERS_QUERY
// Query: *[  _type == "order"] | order(createdAt desc) [0...$limit] {  _id,  orderNumber,  email,  total,  status,  createdAt}
export type RECENT_ORDERS_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  email: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
}>;
// Variable: ORDER_BY_STRIPE_PAYMENT_ID_QUERY
// Query: *[  _type == "order"  && stripePaymentId == $stripePaymentId][0]{ _id }
export type ORDER_BY_STRIPE_PAYMENT_ID_QUERYResult = {
  _id: string;
} | null;

// Source: ./sanity/queries/products.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[  _type == "product"                    // 1. FILTER: only product documents] | order(name asc) {                   // 2. SORT: alphabetical by name  _id,  name,  "slug": slug.current,                 // 3. Rename: make slug a clean string  description,  price,  "images": images[]{                   // 4. ALL images (no limit)    _key,    asset->{ _id, url },    hotspot  },  category->{                           // 5. Expand category reference    _id, title, "slug": slug.current  },  material, color, dimensions,  stock, featured, assemblyRequired}
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[  _type == "product"                    // 1. Base type filter  && featured == true                   // 2. Must be marked featured  && stock > 0                          // 3. Must be in stock] | order(name asc) [0...6] {           // 4. Sort A-Z → take first 6 (exclusive)  _id, name, "slug": slug.current,  description, price,  "images": images[]{ _key, asset->{ _id, url }, hotspot },  category->{ _id, title, "slug": slug.current },  stock}
export type FEATURED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
}>;
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[  _type == "product"                    // 1. Base filter  && category->slug.current == $categorySlug   // 2. Exact category match] | order(name asc) {                   // 3. SORT: alphabetical  _id, name, "slug": slug.current,  price,  "image": images[0]{                   // 4. Only first image    asset->{ _id, url }, hotspot  },  category->{ _id, title, "slug": slug.current },  material, color, stock}
export type PRODUCTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[  _type == "product"                    // 1. FILTER: only products  && slug.current == $slug              // 2. MATCH: exact slug from URL][0] {                                  // 3. SELECT: first (and only) result as object  _id, name, "slug": slug.current,  description, price,  "images": images[]{                   // 4. ARRAY: all images for gallery    _key,    asset->{ _id, url },    hotspot  },  category->{                           // 5. JOIN: full category data    _id, title, "slug": slug.current  },  material, color, dimensions,  stock, featured, assemblyRequired}
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
} | null;
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"  && (                                  // 1. Must match name OR description    name match $searchQuery + "*"    || description match $searchQuery + "*"  )] | score(                               // 2. Calculate relevance  boost(name match $searchQuery + "*", 3),  boost(description match $searchQuery + "*", 1)) | order(_score desc) {                // 3. Best match first  _id, _score,                          // 4. Include score in result  name, "slug": slug.current,  price,  "image": images[0]{ asset->{ _id, url }, hotspot },  category->{ _id, title, "slug": slug.current },  material, color, stock}
export type SEARCH_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _score: null;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[  _type == "product"                                                      // 1. BASE FILTER: only products  && ($categorySlug == "" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category  && ($color == ""        || color == $color)                             // 3. OPTIONAL: color  && ($material == ""     || material == $material)                       // 4. OPTIONAL: material  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)  && ($searchQuery == ""  || name match $searchQuery + "*" || description match $searchQuery + "*")  // 7. OPTIONAL: search  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only]        // 1. Apply all optional filters  | order(name asc)                       // 2. SORT: alphabetical  {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)    _key,                            // 2. Needed for React list rendering    asset->{ _id, url }              // 3. Dereference to get real image URL  },  category->{                        // 4. Expand category reference    _id, title, "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_NAME_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[  _type == "product"                                                      // 1. BASE FILTER: only products  && ($categorySlug == "" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category  && ($color == ""        || color == $color)                             // 3. OPTIONAL: color  && ($material == ""     || material == $material)                       // 4. OPTIONAL: material  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)  && ($searchQuery == ""  || name match $searchQuery + "*" || description match $searchQuery + "*")  // 7. OPTIONAL: search  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only]               // 1. All optional filters (category, color, price range, search, stock…)  | order(price asc)                        // 2. SORT: lowest price first (ascending)  {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)    _key,                            // 2. Needed for React list rendering    asset->{ _id, url }              // 3. Dereference to get real image URL  },  category->{                        // 4. Expand category reference    _id, title, "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[  _type == "product"                                                      // 1. BASE FILTER: only products  && ($categorySlug == "" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category  && ($color == ""        || color == $color)                             // 3. OPTIONAL: color  && ($material == ""     || material == $material)                       // 4. OPTIONAL: material  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)  && ($searchQuery == ""  || name match $searchQuery + "*" || description match $searchQuery + "*")  // 7. OPTIONAL: search  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only]               // 1. Same optional filters  | order(price desc)                       // 2. SORT: highest price first (descending)  {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)    _key,                            // 2. Needed for React list rendering    asset->{ _id, url }              // 3. Dereference to get real image URL  },  category->{                        // 4. Expand category reference    _id, title, "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[  _type == "product"                                                      // 1. BASE FILTER: only products  && ($categorySlug == "" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category  && ($color == ""        || color == $color)                             // 3. OPTIONAL: color  && ($material == ""     || material == $material)                       // 4. OPTIONAL: material  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)  && ($searchQuery == ""  || name match $searchQuery + "*" || description match $searchQuery + "*")  // 7. OPTIONAL: search  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only]               // 1. All optional filters still apply  | score(  boost(name match $searchQuery + "*", 3),        // Title = very important  boost(description match $searchQuery + "*", 1)  // Description = secondary)                      // 2. Compute relevance score                                            //    → title matches 3× stronger                                            //    → _score added automatically (runtime)  | order(_score desc, name asc)            // 3. Best score first → then A-Z on ties  {  _id,  name,  "slug": slug.current,  price,  "images": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)    _key,                            // 2. Needed for React list rendering    asset->{ _id, url }              // 3. Dereference to get real image URL  },  category->{                        // 4. Expand category reference    _id, title, "slug": slug.current  },  material,  color,  stock}
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  stock: number | null;
}>;
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[  _type == "product"  && _id in $ids                        // 1. Match any ID in array] {  _id, name, "slug": slug.current,  price,  "image": images[0]{ asset->{ _id, url }, hotspot },  stock                                 // 2. Critical for availability check}
export type PRODUCTS_BY_IDS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  stock: number | null;
}>;
// Variable: LOW_STOCK_PRODUCTS_QUERY
// Query: *[  _type == "product"                    // 1. Base filter  && stock > 0                          // 2. Still available  && stock <= 5    // 3. Below threshold (e.g. 5)] | order(stock asc) {                  // 4. SORT: lowest stock first  _id, name, "slug": slug.current,  stock,  "image": images[0]{                   // 5. Only first image    asset->{ _id, url }  }}
export type LOW_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  stock: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: OUT_OF_STOCK_PRODUCTS_QUERY
// Query: *[  _type == "product"  && stock == 0                         // 1. Only out-of-stock] | order(name asc) {                   // 2. SORT: A-Z  _id, name, "slug": slug.current,  "image": images[0]{ asset->{ _id, url } }}
export type OUT_OF_STOCK_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: AI_SEARCH_PRODUCTS_QUERY
// Query: *[  _type == "product"                    // 1. Base filter  && (                                  // 2. Broad search condition    $searchQuery == ""                  //   - no query = return all    || name match $searchQuery + "*"    || description match $searchQuery + "*"    || category->title match $searchQuery + "*"  // extra: category names  )  && ($categorySlug == "" || category->slug.current == $categorySlug)  && ($material == "" || material == $material)  && ($color == "" || color == $color)  && ($minPrice == 0 || price >= $minPrice)  && ($maxPrice == 0 || price <= $maxPrice)] | order(name asc) [0...20] {           // 3. SORT A-Z + limit to 20  _id, name, "slug": slug.current,  description, price,  "image": images[0]{ asset->{ _id, url } },  category->{ _id, title, "slug": slug.current },  material, color, dimensions,  stock, featured, assemblyRequired}
export type AI_SEARCH_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  material: "fabric" | "glass" | "leather" | "metal" | "wood" | null;
  color: "black" | "grey" | "natural" | "oak" | "walnut" | "white" | null;
  dimensions: string | null;
  stock: number | null;
  featured: boolean | null;
  assemblyRequired: boolean | null;
}>;

// Source: ./sanity/queries/stats.ts
// Variable: PRODUCT_COUNT_QUERY
// Query: count(*[_type == "product"])
export type PRODUCT_COUNT_QUERYResult = number;
// Variable: ORDER_COUNT_QUERY
// Query: count(*[_type == "order"])
export type ORDER_COUNT_QUERYResult = number;
// Variable: TOTAL_REVENUE_QUERY
// Query: math::sum(*[  _type == "order"  && status in ["paid", "shipped", "delivered"]].total)
export type TOTAL_REVENUE_QUERYResult = number;
// Variable: ORDERS_LAST_7_DAYS_QUERY
// Query: *[  _type == "order"  && createdAt >= $startDate  && !(_id in path("drafts.**"))] | order(createdAt desc) {  _id,  orderNumber,  total,  status,  createdAt,  "itemCount": count(items),  items[]{    quantity,    priceAtPurchase,    "productName": product->name,    "productId": product->_id  }}
export type ORDERS_LAST_7_DAYS_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  total: number | null;
  status: "cancelled" | "delivered" | "paid" | "shipped" | null;
  createdAt: string | null;
  itemCount: number | null;
  items: Array<{
    quantity: number | null;
    priceAtPurchase: number | null;
    productName: string | null;
    productId: string | null;
  }> | null;
}>;
// Variable: ORDER_STATUS_DISTRIBUTION_QUERY
// Query: {  "paid": count(*[_type == "order" && status == "paid" && !(_id in path("drafts.**"))]),  "shipped": count(*[_type == "order" && status == "shipped" && !(_id in path("drafts.**"))]),  "delivered": count(*[_type == "order" && status == "delivered" && !(_id in path("drafts.**"))]),  "cancelled": count(*[_type == "order" && status == "cancelled" && !(_id in path("drafts.**"))])}
export type ORDER_STATUS_DISTRIBUTION_QUERYResult = {
  paid: number;
  shipped: number;
  delivered: number;
  cancelled: number;
};
// Variable: REVENUE_BY_PERIOD_QUERY
// Query: {  "currentPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ].total),  "previousPeriod": math::sum(*[    _type == "order"    && status in ["paid", "shipped", "delivered"]    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ].total),  "currentOrderCount": count(*[    _type == "order"    && createdAt >= $currentStart    && !(_id in path("drafts.**"))  ]),  "previousOrderCount": count(*[    _type == "order"    && createdAt >= $previousStart    && createdAt < $currentStart    && !(_id in path("drafts.**"))  ])}
export type REVENUE_BY_PERIOD_QUERYResult = {
  currentPeriod: number;
  previousPeriod: number;
  currentOrderCount: number;
  previousOrderCount: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[ \n  _type == \"category\" \n] | order(title asc) { \n  _id,                 \n  title,               \n  \"slug\": slug.current,\n  \"image\": image {     \n    asset-> {         \n      _id,             \n      url             \n    },                 \n    hotspot          \n  }\n}": ALL_CATEGORIES_QUERYResult;
    "*[\n  _type == \"category\"\n  && slug.current == $slug\n][0] {\n  _id,\n  title,\n  \"slug\": slug.current,\n  \"image\": image{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}": CATEGORY_BY_SLUG_QUERYResult;
    "*[\n  _type == \"customer\"\n  && email == $email\n][0] {\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}": CUSTOMER_BY_EMAIL_QUERYResult;
    "*[\n  _type == \"customer\"\n  && stripeCustomerId == $stripeCustomerId\n][0] {\n  _id,\n  email,\n  name,\n  clerkUserId,\n  stripeCustomerId,\n  createdAt\n}": CUSTOMER_BY_STRIPE_ID_QUERYResult;
    "*[\n  _type == \"order\"\n  && clerkUserId == $clerkUserId\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  \"itemCount\": count(items),\n  \"itemNames\": items[].product->name,\n  \"itemImages\": items[].product->images[0].asset->url\n}": ORDERS_BY_USER_QUERYResult;
    "*[\n  _type == \"order\"\n  && _id == $id\n][0] {\n  _id,\n  orderNumber,\n  clerkUserId,\n  email,\n  items[]{\n    _key,\n    quantity,\n    priceAtPurchase,\n    product->{\n      _id,\n      name,\n      \"slug\": slug.current,\n      \"image\": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  },\n  total,\n  status,\n  address{\n    name,\n    line1,\n    line2,\n    city,\n    postcode,\n    country\n  },\n  stripePaymentId,\n  createdAt\n}": ORDER_BY_ID_QUERYResult;
    "*[\n  _type == \"order\"\n] | order(createdAt desc) [0...$limit] {\n  _id,\n  orderNumber,\n  email,\n  total,\n  status,\n  createdAt\n}": RECENT_ORDERS_QUERYResult;
    "*[\n  _type == \"order\"\n  && stripePaymentId == $stripePaymentId\n][0]{ _id }": ORDER_BY_STRIPE_PAYMENT_ID_QUERYResult;
    "*[\n  _type == \"product\"                    // 1. FILTER: only product documents\n] | order(name asc) {                   // 2. SORT: alphabetical by name\n  _id,\n  name,\n  \"slug\": slug.current,                 // 3. Rename: make slug a clean string\n  description,\n  price,\n  \"images\": images[]{                   // 4. ALL images (no limit)\n    _key,\n    asset->{ _id, url },\n    hotspot\n  },\n  category->{                           // 5. Expand category reference\n    _id, title, \"slug\": slug.current\n  },\n  material, color, dimensions,\n  stock, featured, assemblyRequired\n}": ALL_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"                    // 1. Base type filter\n  && featured == true                   // 2. Must be marked featured\n  && stock > 0                          // 3. Must be in stock\n] | order(name asc) [0...6] {           // 4. Sort A-Z \u2192 take first 6 (exclusive)\n  _id, name, \"slug\": slug.current,\n  description, price,\n  \"images\": images[]{ _key, asset->{ _id, url }, hotspot },\n  category->{ _id, title, \"slug\": slug.current },\n  stock\n}": FEATURED_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"                    // 1. Base filter\n  && category->slug.current == $categorySlug   // 2. Exact category match\n] | order(name asc) {                   // 3. SORT: alphabetical\n  _id, name, \"slug\": slug.current,\n  price,\n  \"image\": images[0]{                   // 4. Only first image\n    asset->{ _id, url }, hotspot\n  },\n  category->{ _id, title, \"slug\": slug.current },\n  material, color, stock\n}": PRODUCTS_BY_CATEGORY_QUERYResult;
    "*[\n  _type == \"product\"                    // 1. FILTER: only products\n  && slug.current == $slug              // 2. MATCH: exact slug from URL\n][0] {                                  // 3. SELECT: first (and only) result as object\n  _id, name, \"slug\": slug.current,\n  description, price,\n  \"images\": images[]{                   // 4. ARRAY: all images for gallery\n    _key,\n    asset->{ _id, url },\n    hotspot\n  },\n  category->{                           // 5. JOIN: full category data\n    _id, title, \"slug\": slug.current\n  },\n  material, color, dimensions,\n  stock, featured, assemblyRequired\n}": PRODUCT_BY_SLUG_QUERYResult;
    "*[\n  _type == \"product\"\n  && (                                  // 1. Must match name OR description\n    name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n  )\n] | score(                               // 2. Calculate relevance\n  boost(name match $searchQuery + \"*\", 3),\n  boost(description match $searchQuery + \"*\", 1)\n) | order(_score desc) {                // 3. Best match first\n  _id, _score,                          // 4. Include score in result\n  name, \"slug\": slug.current,\n  price,\n  \"image\": images[0]{ asset->{ _id, url }, hotspot },\n  category->{ _id, title, \"slug\": slug.current },\n  material, color, stock\n}": SEARCH_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"                                                      // 1. BASE FILTER: only products\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category\n  && ($color == \"\"        || color == $color)                             // 3. OPTIONAL: color\n  && ($material == \"\"     || material == $material)                       // 4. OPTIONAL: material\n  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)\n  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)\n  && ($searchQuery == \"\"  || name match $searchQuery + \"*\" || description match $searchQuery + \"*\")  // 7. OPTIONAL: search\n  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only\n]        // 1. Apply all optional filters\n  | order(name asc)                       // 2. SORT: alphabetical\n  {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)\n    _key,                            // 2. Needed for React list rendering\n    asset->{ _id, url }              // 3. Dereference to get real image URL\n  },\n  category->{                        // 4. Expand category reference\n    _id, title, \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_NAME_QUERYResult;
    "*[\n  _type == \"product\"                                                      // 1. BASE FILTER: only products\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category\n  && ($color == \"\"        || color == $color)                             // 3. OPTIONAL: color\n  && ($material == \"\"     || material == $material)                       // 4. OPTIONAL: material\n  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)\n  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)\n  && ($searchQuery == \"\"  || name match $searchQuery + \"*\" || description match $searchQuery + \"*\")  // 7. OPTIONAL: search\n  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only\n]               // 1. All optional filters (category, color, price range, search, stock\u2026)\n  | order(price asc)                        // 2. SORT: lowest price first (ascending)\n  {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)\n    _key,                            // 2. Needed for React list rendering\n    asset->{ _id, url }              // 3. Dereference to get real image URL\n  },\n  category->{                        // 4. Expand category reference\n    _id, title, \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_PRICE_ASC_QUERYResult;
    "*[\n  _type == \"product\"                                                      // 1. BASE FILTER: only products\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category\n  && ($color == \"\"        || color == $color)                             // 3. OPTIONAL: color\n  && ($material == \"\"     || material == $material)                       // 4. OPTIONAL: material\n  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)\n  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)\n  && ($searchQuery == \"\"  || name match $searchQuery + \"*\" || description match $searchQuery + \"*\")  // 7. OPTIONAL: search\n  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only\n]               // 1. Same optional filters\n  | order(price desc)                       // 2. SORT: highest price first (descending)\n  {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)\n    _key,                            // 2. Needed for React list rendering\n    asset->{ _id, url }              // 3. Dereference to get real image URL\n  },\n  category->{                        // 4. Expand category reference\n    _id, title, \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_PRICE_DESC_QUERYResult;
    "*[\n  _type == \"product\"                                                      // 1. BASE FILTER: only products\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)     // 2. OPTIONAL: category\n  && ($color == \"\"        || color == $color)                             // 3. OPTIONAL: color\n  && ($material == \"\"     || material == $material)                       // 4. OPTIONAL: material\n  && ($minPrice == 0      || price >= $minPrice)                          // 5. OPTIONAL: min price (0 = no limit)\n  && ($maxPrice == 0      || price <= $maxPrice)                          // 6. OPTIONAL: max price (0 = no limit)\n  && ($searchQuery == \"\"  || name match $searchQuery + \"*\" || description match $searchQuery + \"*\")  // 7. OPTIONAL: search\n  && ($inStock == false   || stock > 0)                                   // 8. OPTIONAL: in-stock only\n]               // 1. All optional filters still apply\n  | score(\n  boost(name match $searchQuery + \"*\", 3),        // Title = very important\n  boost(description match $searchQuery + \"*\", 1)  // Description = secondary\n)                      // 2. Compute relevance score\n                                            //    \u2192 title matches 3\xD7 stronger\n                                            //    \u2192 _score added automatically (runtime)\n  | order(_score desc, name asc)            // 3. Best score first \u2192 then A-Z on ties\n  {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  \"images\": images[0...4]{           // 1. LIMIT: max 4 images (exclusive)\n    _key,                            // 2. Needed for React list rendering\n    asset->{ _id, url }              // 3. Dereference to get real image URL\n  },\n  category->{                        // 4. Expand category reference\n    _id, title, \"slug\": slug.current\n  },\n  material,\n  color,\n  stock\n}": FILTER_PRODUCTS_BY_RELEVANCE_QUERYResult;
    "*[\n  _type == \"product\"\n  && _id in $ids                        // 1. Match any ID in array\n] {\n  _id, name, \"slug\": slug.current,\n  price,\n  \"image\": images[0]{ asset->{ _id, url }, hotspot },\n  stock                                 // 2. Critical for availability check\n}": PRODUCTS_BY_IDS_QUERYResult;
    "*[\n  _type == \"product\"                    // 1. Base filter\n  && stock > 0                          // 2. Still available\n  && stock <= 5    // 3. Below threshold (e.g. 5)\n] | order(stock asc) {                  // 4. SORT: lowest stock first\n  _id, name, \"slug\": slug.current,\n  stock,\n  \"image\": images[0]{                   // 5. Only first image\n    asset->{ _id, url }\n  }\n}": LOW_STOCK_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"\n  && stock == 0                         // 1. Only out-of-stock\n] | order(name asc) {                   // 2. SORT: A-Z\n  _id, name, \"slug\": slug.current,\n  \"image\": images[0]{ asset->{ _id, url } }\n}": OUT_OF_STOCK_PRODUCTS_QUERYResult;
    "*[\n  _type == \"product\"                    // 1. Base filter\n  && (                                  // 2. Broad search condition\n    $searchQuery == \"\"                  //   - no query = return all\n    || name match $searchQuery + \"*\"\n    || description match $searchQuery + \"*\"\n    || category->title match $searchQuery + \"*\"  // extra: category names\n  )\n  && ($categorySlug == \"\" || category->slug.current == $categorySlug)\n  && ($material == \"\" || material == $material)\n  && ($color == \"\" || color == $color)\n  && ($minPrice == 0 || price >= $minPrice)\n  && ($maxPrice == 0 || price <= $maxPrice)\n] | order(name asc) [0...20] {           // 3. SORT A-Z + limit to 20\n  _id, name, \"slug\": slug.current,\n  description, price,\n  \"image\": images[0]{ asset->{ _id, url } },\n  category->{ _id, title, \"slug\": slug.current },\n  material, color, dimensions,\n  stock, featured, assemblyRequired\n}": AI_SEARCH_PRODUCTS_QUERYResult;
    "count(*[_type == \"product\"])": PRODUCT_COUNT_QUERYResult;
    "count(*[_type == \"order\"])": ORDER_COUNT_QUERYResult;
    "math::sum(*[\n  _type == \"order\"\n  && status in [\"paid\", \"shipped\", \"delivered\"]\n].total)": TOTAL_REVENUE_QUERYResult;
    "*[\n  _type == \"order\"\n  && createdAt >= $startDate\n  && !(_id in path(\"drafts.**\"))\n] | order(createdAt desc) {\n  _id,\n  orderNumber,\n  total,\n  status,\n  createdAt,\n  \"itemCount\": count(items),\n  items[]{\n    quantity,\n    priceAtPurchase,\n    \"productName\": product->name,\n    \"productId\": product->_id\n  }\n}": ORDERS_LAST_7_DAYS_QUERYResult;
    "{\n  \"paid\": count(*[_type == \"order\" && status == \"paid\" && !(_id in path(\"drafts.**\"))]),\n  \"shipped\": count(*[_type == \"order\" && status == \"shipped\" && !(_id in path(\"drafts.**\"))]),\n  \"delivered\": count(*[_type == \"order\" && status == \"delivered\" && !(_id in path(\"drafts.**\"))]),\n  \"cancelled\": count(*[_type == \"order\" && status == \"cancelled\" && !(_id in path(\"drafts.**\"))])\n}": ORDER_STATUS_DISTRIBUTION_QUERYResult;
    "{\n  \"currentPeriod\": math::sum(*[\n    _type == \"order\"\n    && status in [\"paid\", \"shipped\", \"delivered\"]\n    && createdAt >= $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ].total),\n  \"previousPeriod\": math::sum(*[\n    _type == \"order\"\n    && status in [\"paid\", \"shipped\", \"delivered\"]\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ].total),\n  \"currentOrderCount\": count(*[\n    _type == \"order\"\n    && createdAt >= $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ]),\n  \"previousOrderCount\": count(*[\n    _type == \"order\"\n    && createdAt >= $previousStart\n    && createdAt < $currentStart\n    && !(_id in path(\"drafts.**\"))\n  ])\n}": REVENUE_BY_PERIOD_QUERYResult;
  }
}
